HAI
CAN HAS STDIO?
I HAS A PI ITZ 0
I HAS A num ITZ 4
I HAS A denom ITZ 1
I HAS A MAX ITZ 500000
I HAS A ODD ITZ 0
I HAS A i ITZ 0
IM IN YR WEEEE UPPIN YR i TIL BOTH SAEM i AN BIGGR OF i AN MAX
	BOTH SAEM ODD AN 0
	O RLY?
	YA RLY
		ODD R 1
		PI R SUM OF PI AN QUOSHUNT OF num AN denom
	NO WAI
		ODD R 0
		PI R DIFF OF PI AN QUOSHUNT OF num AN denom
	OIC
	denom R SUM OF denom AN 2
IM OUTTA YR WEEEE
VISIBLE PI
KTHXBYE